# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-19 14:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bucketlist',
        ),
    ]
