# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-20 10:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0005_bucketlist_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bucketlist',
            name='number',
        ),
        migrations.AlterField(
            model_name='bucketlist',
            name='name',
            field=models.CharField(default='', max_length=255, unique=True),
        ),
    ]
